### ISSUE TITLE
Remove unrelated images from repo

### ISSUE THREAD

**Issue by viggyprabhu** [fsmk/consilience15#17]
Let us also remove all the unnecessary images from the repo. Its a copyright violation from our side.

**Comment by abhi12ravi** [comment]
Working on it.

On Tue, Apr 7, 2015 at 6:20 PM, Vignesh Prabhu notifications@github.com
wrote:

> Assigned #17 https://github.com/fsmk/consilience15/issues/17 to
> @abhi12ravi https://github.com/abhi12ravi.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fsmk/consilience15/issues/17#event-275188832.

## 

Regards,
Abhiram Ravikumar
http://abhiramrk.com/

**Comment by abhi12ravi** [comment]
Done
