### ISSUE TITLE
Add Speakers list to the conference website

### ISSUE THREAD

**Issue by viggyprabhu** [fsmk/consilience15#20]
This is the list of confirmed speakers. Kindly find their images and add them in the speakers section. We can remove the Agenda Page as of now and replace with Speakers section as currently the schedule is not decided. Please modify the webpage design accordingly.
You can look at some other conference site on how to present the list of speakers in a one-page site.
These are the confirmed speakers as of now.
Chaitanya Ramachandran (Associate, AMSS)
Nikhil Pahwa (Founder, MediaNama)
Smarika Kumar (Researcher, Alternative Law Forum)
Parminder Jeet Singh (Executive Director, IT for Change)
Rajan Mathews (Director-General, Cellular Operators Association of India)
Raman Chima (Asia Consultant, Access Now)
Joginder Yadav (General Counsel, CISCO India)
Pranesh Prakash (Policy Director, Centre for Internet and Society)
Rishabh Bailey (Consultant, Society for Knowledge Commons)
TV Ramachandran (Resident Director, Regulatory Affairs and Govt. Relations, Vodafone Essar Ltd.)

**Comment by jee1mr** [comment]
Done :+1:
