### ISSUE TITLE
News section

### ISSUE THREAD

**Issue by viggyprabhu** [fsmk/consilience15#32]
This will contain three sub items, one below other. First section, Videos, AIB's Video on netneutrality and [John Oliver's Video](https://www.youtube.com/watch?v=fpbOEoRrHyU). 
Below that, let us put images of companies announcing their coming out of Airtel Zero and Internet.org, like what Flipkart did with Airtel Zero and Cleartrip, NDTV, TimesGroup, newsHunt did with internet.org. We can just take a screenshot of their tweet and put it here.
Below that we can have news items covering Net Neutrality, links of 5 to 10 should be good. Will share it here as comment soon.

**Comment by abhi12ravi** [comment]
@viggyprabhu  Where should this section actually appear?

**Comment by viggyprabhu** [comment]
Hey,

> On April 18, 2015 at 3:42 PM Abhiram Ravikumar notifications@github.com
> wrote:
> 
> @viggyprabhu  Where should this section actually appear?
> This will come below "About" section.

**Comment by abhi12ravi** [comment]
@viggyprabhu Can we close this issue?
