### ISSUE TITLE
Need to add Contact information

### ISSUE THREAD

**Issue by viggyprabhu** [fsmk/consilience15#37]
Contact will be at the end of the Page. Menu item also need to be there at the end.

Following Contact information along with link to Facebook page has to be added. 

Sarthak Gupta  
Convenor,Law and Technology Society., (+91 8095722839)

Saiya Savooji, Joint Convenor, Law and Technology
Society, (+91 9945300850)

Email id: ltech.nls@gmail.com

**Comment by jee1mr** [comment]
done :+1:

**Comment by viggyprabhu** [comment]
Fixed by PR #39
