### ISSUE TITLE
Need to add For and Against section in News Section

### ISSUE THREAD

**Issue by viggyprabhu** [fsmk/consilience15#41]
In the news section, we need to add some articles as For NetNeutrality and some as Against.

In case of For, we should add TimesGroup stand, http://blog.timesinternet.in/times-group-commits-to-withdraw-from-internet-org-appeals-to-fellow-publishers-to-follow-suit-and-support-net-neutrality/ as they are one of the sponsors.

**Comment by viggyprabhu** [comment]
We also need to embed the tweet by TimesGroup in support of NetNeutrality, https://twitter.com/Timesinternet/status/588359103166087168

**Comment by abhi12ravi** [comment]
@viggyprabhu  Can you give me an example of tweets "against" net-neutrality?

**Comment by viggyprabhu** [comment]
Hey,

Not tweets but articles. You can have a subsection like "Views in favour of NetNeutrality". Under it, you can say, "Times Group view on NetNeutrality" when someone clicks it, it should expand showing a brief snippet of the article and have a 'more' link to the original article.
Same for against Netneutrality.
For against, you can use :,
1) MarkZuckerberg's view https://www.facebook.com/zuck/posts/10102033678947881
2) Airtel's mail, https://www.facebook.com/AirtelIndia/photos/a.161184937238467.36727.147351511955143/990076014349351/?type=1
